#!/usr/bin/env bash

echo ---------------------------------------------------------------
echo
echo Hello Human
echo It's shipping time!
echo
echo ---------------------------------------------------------------
echo

npm run release

echo
echo ---------------------------------------------------------------
echo
echo Done!
