#!/usr/bin/env bash

echo ---------------------------------------------------------------
echo
echo Hello Human
echo Let''s see some science!
echo
echo ---------------------------------------------------------------
echo


./node_modules/electron-prebuilt/dist/electron.app/Contents/MacOS/Electron .

echo
echo ---------------------------------------------------------------
echo
echo Done!
