#!/usr/bin/env bash

echo ---------------------------------------------------------------
echo
echo Hello Human
echo It''s shipping time!
echo
echo ---------------------------------------------------------------
echo

npm run release-windows

echo
echo ---------------------------------------------------------------
echo
echo Done!
